#!/usr/bin/env bash

# Brewfile 
# can be run with "brew bundle" 



# Ask for the administrator password upfront.
sudo -v
# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Make sure we’re using the latest Homebrew.
brew update
# Upgrade any already-installed formulae.
brew upgrade --all

## ---------------------------------------------------------------------
# Brew
brew update 
brew doctor


# Taps
# tap adds GitHub repo to list of installable homebrew packages
brew tap Homebrew/bundle


# Casks
# Directory to install (do I still need to specify below?)
cask_args appdir: '~/Applications'
install caskroom/cask/brew-cask

cask install --appdir="~/Applications" dropbox
cask install --appdir="~/Applications" alfred


cask install --appdir="~/Applications" google-chrome
cask install --appdir="~/Applications" firefox
cask install --appdir="~/Applications" evernote

cask install --appdir="~/Applications" seil
cask install --appdir="~/Applications" karabiner
cask install --appdir="~/Applications" keyboard-maestro
cask install --appdir="~/Applications" bettertouchtool
cask install --appdir="~/Applications" slate

cask install --appdir="~/Applications" snagit

cask install --appdir="~/Applications" vlc
cask install --appdir="~/Applications" spotify
cask install --appdir="~/Applications" keepass
cask install --appdir="~/Applications" sublime

cask install --appdir="~/Applications" appcleaner

# Remove outdated versions from the cellar.
brew cleanup